name: "CI (Integration Continuos): Main Workflow"

 # Variaveis de ambiente secreta 
env: 
  VERCEL_TOKEN: "LyBpvh5bAJEVVhoLdPUIhJZ1"
  VERCEL_ORG_ID: "VWvkGCQcPsOZyxYxkHbQ2FQq"
  VERCEL_PROJECT_ID: "prj_1TckW8bSU04Nfzp2Xs22tO7emiKf"
  
on:
  # Ativa o fluxo de trabalho para cada push ou pull na branch main
  push:
  pull_request:
    types: [opened, syschronize]

jobs:
# ====================================== #
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Installation
        run: npm install
      - name: Format code with Prettier
        run: npx prettier --write .
# ====================================== #

# ================================================= #
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Installation
        run: npm install

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Format code with Prettier
        run: npx prettier --write .

      - name: Run Preview Deployment
        run: npm run deploy:preview
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
# ================================================= #

# =============================================== #
  test_e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # https://github.com/actions/setup-node
      - uses: actions/setup-node@v4
        with:
          node-version: 20.15.1

      # https://github.com/cypress-io/github-action | https://docs.cypress.io/app/continuous-integration/github-actions
      - name: Cypress
        uses: cypress-io/github-action@v6
        with: 
          browser: chrome 

      - name: Run Installation
        run: npm install

      - name: Cypress run
        run: npm run test:e2e
# =============================================== #
