name: "CI (Integration Continuos): Main Workflow"

on:
  # Ativa o fluxo de trabalho para cada push ou pull na branch main
  push:
  pull_request:
    types: [opened, syschronize]

jobs:
  linter:
    # Exucutado sistema operacional para executar a operação
    runs-on: ubuntu-latest
    steps:
      # Pré configuração do github para rodar comandos git
      - uses: actions/checkout@v4

       # Executa apenas comandos no shell
      - name: Run Installation
        run: npm install

      - name: Run Linter in Code 1
        run: npm run lint -- --fix

      # Executa apenas comandos no shell
      - name: Run Linter in Code 2
        run: npm run lint
