name: "CI (Integration Continuos): Main Workflow"

 # Variaveis de ambiente secreta
env: 
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID}}
  VERCEL_PROJECT_ID: ${{ secrets.PROJECT_ID}}

on:
  # Ativa o fluxo de trabalho para cada push ou pull na branch main
  push:
  pull_request:
    types: [opened, syschronize]

jobs:
  linter:
    # Exucutado sistema operacional para executar a operação
    runs-on: ubuntu-latest
    steps:
      # Pré configuração do github para rodar comandos git
      - uses: actions/checkout@v4

       # Executa apenas comandos no shell
      - name: Run Installation
        run: npm install
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Installation
        run: npm install
      - name: Run Preview Deployment
        run: npm run deploy:preview
