name: "CI (Integration Continuos): Main Workflow"

# Variáveis de ambiente secretas (armazenadas no GitHub Secrets)
env: 
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID}}
  VERCEL_PROJECT_ID: ${{ secrets.PROJECT_ID}}
  
on:
  # Ativa o fluxo de trabalho para cada push ou pull na branch main
  push:
  pull_request:
    types: [opened, syschronize]

  # push:
  # branches: ["main"]
  # pull_request:
  #   types: [opened, syschronize]

jobs:
# ====================================== #
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Installation
        run: npm install
      - name: Format code with Prettier
        run: npx prettier --write .
# ====================================== #

# ================================================= #
  preview:
    # Define o sistema operacional da máquina virtual onde as ações serão executadas
    runs-on: ubuntu-latest
    steps:
      # Faz o checkout do repositório (baixa o código-fonte)
      - uses: actions/checkout@v4

      # Instala as dependências do projeto
      - name: Run Installation
        run: npm install

      # Instala pacote da vercel
      - name: Install Vercel CLI
        run: npm install -g vercel

      # Formata o código usando o Prettier
      - name: Format code with Prettier
        run: npx prettier --write .

      # Executa o comando de deploy para produção
      - name: Run Preview Deployment
        run: npm run deploy:preview
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
# ================================================= #

# =============================================== #
  test_e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # https://github.com/actions/setup-node
      - uses: actions/setup-node@v4
        with:
          node-version: 20.15.1

      # https://github.com/cypress-io/github-action | https://docs.cypress.io/app/continuous-integration/github-actions
      - name: Cypress
        uses: cypress-io/github-action@v6
        with: 
          browser: chrome 

      # Instala as dependências do projeto
      - name: Run Installation
        run: npm install

      # Executa o comando para iniciar os testes
      - name: Cypress run
        run: npm run test:e2e
# =============================================== #
