name: "CI (Integration Continuos): Primary Action"

# Controls when the workflow will run
on:
  # Ativa o fluxo de trabalho para cada push ou pull na branch main
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Definindo o que queremos executar
jobs:
  exemplo:
    # Exucutado sistema operacional para executar a operação
    runs-on: ubuntu-latest
    steps:
      # Pré configuração do github para rodar comandos git
      - uses: actions/checkout@v4

      # Executas apenas comandos no shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Executas apenas comandos no shell
      - name: Run a list files
        run: ls -la
