name:
  "CD (Devlivery Continuos): Vercel Workflow"

# Variáveis de ambiente secretas (armazenadas no GitHub Secrets)
env:
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID}}
  VERCEL_PROJECT_ID: ${{ secrets.PROJECT_ID}}

# Define os gatilhos que iniciam este workflow
on:
  # Dispara o workflow em pushs na branch main
  push:
    branches: ["main"]

jobs:
  deploy:
    # Define o sistema operacional da máquina virtual onde as ações serão executadas
    runs-on: ubuntu-latest

    steps:
      # Faz o checkout do repositório (baixa o código-fonte)
      - uses: actions/checkout@v4

      # Instala as dependências do projeto
      - name: Run Installation
        run: npm install

      # Formata o código usando o Prettier
      - name: Format code with Prettier
        run: npx prettier --write .

      # Executa o comando de deploy para produção
      - name: Run Deploy
        run: npm run deploy:prod
